version: '3.3'
services:
  rrhh_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'rrhh_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'secret'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ~/mysql_rrhh_vol:/var/lib/mysql
# Names our volume
volumes:
  my-db:
